name: my_si

on:
  push:
    branches: [dev, main]

  pull_request:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: install build-essential
        run: sudo apt install build-essential

      - name: install lcov
        run: sudo apt install lcov

      - name: install valgrind
        run: sudo apt install valgrind

      - name: install git
        run: sudo apt install git

      - name: install gtest
        run: sudo apt install libgtest-dev

      - name: build project
        run: make build-project

      - name: run tests
        run: make run-all-tests

      - name: get coverage
        run: make coverage

      - name: cov
        uses: actions/upload-artifact@v2
        with:
          name: cov
          path: build/src/storage-device/CMakeFiles/storage.dir/coverage

